apps:browser-extension:
  - changed-files:
      - any-glob-to-any-file:
          - apps/browser-extension/*
          - apps/browser-extension/**/*
apps:discord-bot:
  - changed-files:
      - any-glob-to-any-file:
          - apps/discord-bot/*
          - apps/discord-bot/**/*
apps:website:
  - changed-files:
      - any-glob-to-any-file:
          - apps/website/*
          - apps/website/**/*
dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - pnpm-lock.yaml
packages:components:
  - changed-files:
      - any-glob-to-any-file:
          - packages/components/*
          - packages/components/**/*
packages:engine:
  - changed-files:
      - any-glob-to-any-file:
          - packages/engine/*
          - packages/engine/**/*
packages:env:
  - changed-files:
      - any-glob-to-any-file:
          - packages/env/*
          - packages/env/**/*
packages:helpers:
  - changed-files:
      - any-glob-to-any-file:
          - packages/helpers/*
          - packages/helpers/**/*
packages:hooks:
  - changed-files:
      - any-glob-to-any-file:
          - packages/hooks/*
          - packages/hooks/**/*
packages:style:
  - changed-files:
      - any-glob-to-any-file:
          - packages/style/*
          - packages/style/**/*
packages:types:
  - changed-files:
      - any-glob-to-any-file:
          - packages/types/*
          - packages/types/**/*
